// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gokeeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoKeeper_Registration_FullMethodName = "/gokeeper.GoKeeper/Registration"
	GoKeeper_Login_FullMethodName        = "/gokeeper.GoKeeper/Login"
	GoKeeper_Add_FullMethodName          = "/gokeeper.GoKeeper/Add"
	GoKeeper_Edit_FullMethodName         = "/gokeeper.GoKeeper/Edit"
	GoKeeper_Delete_FullMethodName       = "/gokeeper.GoKeeper/Delete"
	GoKeeper_FindAll_FullMethodName      = "/gokeeper.GoKeeper/FindAll"
)

// GoKeeperClient is the client API for GoKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoKeeperClient interface {
	Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	Add(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Edit(ctx context.Context, in *DataEditRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	FindAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DataList, error)
}

type goKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGoKeeperClient(cc grpc.ClientConnInterface) GoKeeperClient {
	return &goKeeperClient{cc}
}

func (c *goKeeperClient) Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, GoKeeper_Registration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, GoKeeper_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) Add(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, GoKeeper_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) Edit(ctx context.Context, in *DataEditRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, GoKeeper_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, GoKeeper_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goKeeperClient) FindAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DataList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataList)
	err := c.cc.Invoke(ctx, GoKeeper_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoKeeperServer is the server API for GoKeeper service.
// All implementations must embed UnimplementedGoKeeperServer
// for forward compatibility.
type GoKeeperServer interface {
	Registration(context.Context, *RegistrationRequest) (*TokenResponse, error)
	Login(context.Context, *LoginRequest) (*TokenResponse, error)
	Add(context.Context, *DataRequest) (*DataResponse, error)
	Edit(context.Context, *DataEditRequest) (*DataResponse, error)
	Delete(context.Context, *IdRequest) (*SuccessResponse, error)
	FindAll(context.Context, *EmptyRequest) (*DataList, error)
	mustEmbedUnimplementedGoKeeperServer()
}

// UnimplementedGoKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoKeeperServer struct{}

func (UnimplementedGoKeeperServer) Registration(context.Context, *RegistrationRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedGoKeeperServer) Login(context.Context, *LoginRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGoKeeperServer) Add(context.Context, *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedGoKeeperServer) Edit(context.Context, *DataEditRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedGoKeeperServer) Delete(context.Context, *IdRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGoKeeperServer) FindAll(context.Context, *EmptyRequest) (*DataList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedGoKeeperServer) mustEmbedUnimplementedGoKeeperServer() {}
func (UnimplementedGoKeeperServer) testEmbeddedByValue()                  {}

// UnsafeGoKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoKeeperServer will
// result in compilation errors.
type UnsafeGoKeeperServer interface {
	mustEmbedUnimplementedGoKeeperServer()
}

func RegisterGoKeeperServer(s grpc.ServiceRegistrar, srv GoKeeperServer) {
	// If the following call pancis, it indicates UnimplementedGoKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoKeeper_ServiceDesc, srv)
}

func _GoKeeper_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_Registration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).Registration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).Add(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).Edit(ctx, req.(*DataEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoKeeper_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoKeeperServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoKeeper_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoKeeperServer).FindAll(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoKeeper_ServiceDesc is the grpc.ServiceDesc for GoKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gokeeper.GoKeeper",
	HandlerType: (*GoKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _GoKeeper_Registration_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GoKeeper_Login_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _GoKeeper_Add_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _GoKeeper_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoKeeper_Delete_Handler,
		},
		{
			MethodName: "FindAll",
			Handler:    _GoKeeper_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gokeeper.proto",
}
