// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gokeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_gokeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEditRequest) Reset() {
	*x = TextEditRequest{}
	mi := &file_gokeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEditRequest) ProtoMessage() {}

func (x *TextEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEditRequest.ProtoReflect.Descriptor instead.
func (*TextEditRequest) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{1}
}

func (x *TextEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextEditRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_gokeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{2}
}

func (x *TextResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TextResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_gokeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{3}
}

func (x *CardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type CardEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardEditRequest) Reset() {
	*x = CardEditRequest{}
	mi := &file_gokeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardEditRequest) ProtoMessage() {}

func (x *CardEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardEditRequest.ProtoReflect.Descriptor instead.
func (*CardEditRequest) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{4}
}

func (x *CardEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardEditRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_gokeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{5}
}

func (x *CardResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CardResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_gokeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{6}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_gokeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gokeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_gokeeper_proto_rawDescGZIP(), []int{7}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gokeeper_proto protoreflect.FileDescriptor

const file_gokeeper_proto_rawDesc = "" +
	"\n" +
	"\x0egokeeper.proto\x12\bgokeeper\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"5\n" +
	"\x0fTextEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"j\n" +
	"\fTextResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\"%\n" +
	"\vCardRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"9\n" +
	"\x0fCardEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"n\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf8\x02\n" +
	"\bGoKeeper\x128\n" +
	"\aAddText\x12\x15.gokeeper.TextRequest\x1a\x16.gokeeper.TextResponse\x12=\n" +
	"\bEditText\x12\x19.gokeeper.TextEditRequest\x1a\x16.gokeeper.TextResponse\x12<\n" +
	"\n" +
	"DeleteText\x12\x13.gokeeper.IdRequest\x1a\x19.gokeeper.SuccessResponse\x128\n" +
	"\aAddCard\x12\x15.gokeeper.CardRequest\x1a\x16.gokeeper.CardResponse\x12=\n" +
	"\bEditCard\x12\x19.gokeeper.CardEditRequest\x1a\x16.gokeeper.CardResponse\x12<\n" +
	"\n" +
	"DeleteCard\x12\x13.gokeeper.IdRequest\x1a\x19.gokeeper.SuccessResponseB:Z8github.com/bubaew95/yandex-diplom-2/internal/proto;protob\x06proto3"

var (
	file_gokeeper_proto_rawDescOnce sync.Once
	file_gokeeper_proto_rawDescData []byte
)

func file_gokeeper_proto_rawDescGZIP() []byte {
	file_gokeeper_proto_rawDescOnce.Do(func() {
		file_gokeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gokeeper_proto_rawDesc), len(file_gokeeper_proto_rawDesc)))
	})
	return file_gokeeper_proto_rawDescData
}

var file_gokeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gokeeper_proto_goTypes = []any{
	(*TextRequest)(nil),     // 0: gokeeper.TextRequest
	(*TextEditRequest)(nil), // 1: gokeeper.TextEditRequest
	(*TextResponse)(nil),    // 2: gokeeper.TextResponse
	(*CardRequest)(nil),     // 3: gokeeper.CardRequest
	(*CardEditRequest)(nil), // 4: gokeeper.CardEditRequest
	(*CardResponse)(nil),    // 5: gokeeper.CardResponse
	(*IdRequest)(nil),       // 6: gokeeper.IdRequest
	(*SuccessResponse)(nil), // 7: gokeeper.SuccessResponse
}
var file_gokeeper_proto_depIdxs = []int32{
	0, // 0: gokeeper.GoKeeper.AddText:input_type -> gokeeper.TextRequest
	1, // 1: gokeeper.GoKeeper.EditText:input_type -> gokeeper.TextEditRequest
	6, // 2: gokeeper.GoKeeper.DeleteText:input_type -> gokeeper.IdRequest
	3, // 3: gokeeper.GoKeeper.AddCard:input_type -> gokeeper.CardRequest
	4, // 4: gokeeper.GoKeeper.EditCard:input_type -> gokeeper.CardEditRequest
	6, // 5: gokeeper.GoKeeper.DeleteCard:input_type -> gokeeper.IdRequest
	2, // 6: gokeeper.GoKeeper.AddText:output_type -> gokeeper.TextResponse
	2, // 7: gokeeper.GoKeeper.EditText:output_type -> gokeeper.TextResponse
	7, // 8: gokeeper.GoKeeper.DeleteText:output_type -> gokeeper.SuccessResponse
	5, // 9: gokeeper.GoKeeper.AddCard:output_type -> gokeeper.CardResponse
	5, // 10: gokeeper.GoKeeper.EditCard:output_type -> gokeeper.CardResponse
	7, // 11: gokeeper.GoKeeper.DeleteCard:output_type -> gokeeper.SuccessResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gokeeper_proto_init() }
func file_gokeeper_proto_init() {
	if File_gokeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gokeeper_proto_rawDesc), len(file_gokeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gokeeper_proto_goTypes,
		DependencyIndexes: file_gokeeper_proto_depIdxs,
		MessageInfos:      file_gokeeper_proto_msgTypes,
	}.Build()
	File_gokeeper_proto = out.File
	file_gokeeper_proto_goTypes = nil
	file_gokeeper_proto_depIdxs = nil
}
