-- +goose Up
CREATE TABLE cards(
  id SERIAL primary key,
  user_id INTEGER DEFAULT NULL,
  number TEXT DEFAULT NULL,
  is_deleted BOOLEAN DEFAULT FALSE,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE cards ADD CONSTRAINT FK_USER_CARDS FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX IDX_USER_CARDS ON cards (user_Id);

-- +goose Down
ALTER TABLE cards DROP CONSTRAINT FK_USER_CARDS;
DROP TABLE cards;