// Code generated by mockery v2.52.2. DO NOT EDIT.

package client

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/bubaew95/yandex-diplom-2/internal/proto"
)

// MockGoKeeperClient is an autogenerated mock type for the GoKeeperClient type
type MockGoKeeperClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) Add(ctx context.Context, in *proto.DataRequest, opts ...grpc.CallOption) (*proto.DataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *proto.DataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DataRequest, ...grpc.CallOption) (*proto.DataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DataRequest, ...grpc.CallOption) *proto.DataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) Delete(ctx context.Context, in *proto.IdRequest, opts ...grpc.CallOption) (*proto.SuccessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *proto.SuccessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.IdRequest, ...grpc.CallOption) (*proto.SuccessResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.IdRequest, ...grpc.CallOption) *proto.SuccessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SuccessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.IdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Edit provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) Edit(ctx context.Context, in *proto.DataEditRequest, opts ...grpc.CallOption) (*proto.DataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 *proto.DataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DataEditRequest, ...grpc.CallOption) (*proto.DataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DataEditRequest, ...grpc.CallOption) *proto.DataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DataEditRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) FindAll(ctx context.Context, in *proto.EmptyRequest, opts ...grpc.CallOption) (*proto.DataList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 *proto.DataList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EmptyRequest, ...grpc.CallOption) (*proto.DataList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EmptyRequest, ...grpc.CallOption) *proto.DataList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.EmptyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) Login(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.TokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *proto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.TokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.TokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Registration provides a mock function with given fields: ctx, in, opts
func (_m *MockGoKeeperClient) Registration(ctx context.Context, in *proto.RegistrationRequest, opts ...grpc.CallOption) (*proto.TokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Registration")
	}

	var r0 *proto.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegistrationRequest, ...grpc.CallOption) (*proto.TokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegistrationRequest, ...grpc.CallOption) *proto.TokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RegistrationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGoKeeperClient creates a new instance of MockGoKeeperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoKeeperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoKeeperClient {
	mock := &MockGoKeeperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
