// Code generated by mockery v2.52.2. DO NOT EDIT.

package service

import (
	context "context"

	model "github.com/bubaew95/yandex-diplom-2/internal/model"
	mock "github.com/stretchr/testify/mock"

	proto "github.com/bubaew95/yandex-diplom-2/internal/proto"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// AddText provides a mock function with given fields: ctx, r, userID
func (_m *MockRepository) AddText(ctx context.Context, r *model.Data, userID int64) (int64, error) {
	ret := _m.Called(ctx, r, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddText")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Data, int64) (int64, error)); ok {
		return rf(ctx, r, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Data, int64) int64); ok {
		r0 = rf(ctx, r, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Data, int64) error); ok {
		r1 = rf(ctx, r, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, r
func (_m *MockRepository) CreateUser(ctx context.Context, r *model.RegistrationDTO) (int64, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationDTO) (int64, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationDTO) int64); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.RegistrationDTO) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID, ID
func (_m *MockRepository) Delete(ctx context.Context, userID int64, ID int64) error {
	ret := _m.Called(ctx, userID, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Edit provides a mock function with given fields: ctx, r, userID
func (_m *MockRepository) Edit(ctx context.Context, r *model.TextRequest, userID int64) (int64, error) {
	ret := _m.Called(ctx, r, userID)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextRequest, int64) (int64, error)); ok {
		return rf(ctx, r, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextRequest, int64) int64); ok {
		r0 = rf(ctx, r, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TextRequest, int64) error); ok {
		r1 = rf(ctx, r, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, userID
func (_m *MockRepository) FindAll(ctx context.Context, userID int64) ([]*proto.DataResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*proto.DataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*proto.DataResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*proto.DataResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, r
func (_m *MockRepository) FindUserByEmail(ctx context.Context, r *model.LoginDTO) (model.User, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginDTO) (model.User, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginDTO) model.User); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.LoginDTO) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
