// Code generated by mockery v2.52.2. DO NOT EDIT.

package grpc

import (
	context "context"

	model "github.com/bubaew95/yandex-diplom-2/internal/model"
	mock "github.com/stretchr/testify/mock"

	proto "github.com/bubaew95/yandex-diplom-2/internal/proto"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, r
func (_m *MockService) Add(ctx context.Context, r *model.Data) (model.TextResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 model.TextResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Data) (model.TextResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Data) model.TextResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.TextResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Data) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, r
func (_m *MockService) CreateUser(ctx context.Context, r *model.RegistrationDTO) (*model.AuthResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationDTO) (*model.AuthResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationDTO) *model.AuthResponse); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.RegistrationDTO) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, ID
func (_m *MockService) Delete(ctx context.Context, ID int64) error {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Edit provides a mock function with given fields: ctx, r
func (_m *MockService) Edit(ctx context.Context, r *model.TextRequest) (model.TextResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 model.TextResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextRequest) (model.TextResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TextRequest) model.TextResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.TextResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TextRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockService) FindAll(ctx context.Context) ([]*proto.DataResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*proto.DataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*proto.DataResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*proto.DataResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUser provides a mock function with given fields: ctx, r
func (_m *MockService) FindUser(ctx context.Context, r *model.LoginDTO) (model.AuthResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for FindUser")
	}

	var r0 model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginDTO) (model.AuthResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginDTO) model.AuthResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.LoginDTO) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
