// Code generated by mockery v2.52.2. DO NOT EDIT.

package handlers

import (
	context "context"

	model "github.com/bubaew95/yandex-diplom-2/internal/application/server/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, r
func (_m *MockService) AddUser(ctx context.Context, r *model.RegistrationRequest) (model.RegistrationResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 model.RegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationRequest) (model.RegistrationResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegistrationRequest) model.RegistrationResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.RegistrationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.RegistrationRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, r
func (_m *MockService) Login(ctx context.Context, r *model.LoginRequest) (model.AuthResponse, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginRequest) (model.AuthResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.LoginRequest) model.AuthResponse); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(model.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.LoginRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
